### ISSUE TITLE
Theme import isn't working

### ISSUE THREAD

**Issue by tuetschek** [kasnerz/multiling-o-cs#1]
Not sure what I'm not doing right, but when I try to import the theme, I get an error and nothing gets imported (see the attached screenshot)

![Screenshot_20221127-091519_Multiling O Keyboard](https://user-images.githubusercontent.com/2931158/204126014-74832fbf-05b8-4884-89fb-c8808581d5e2.jpg)

**Comment by kasnerz** [comment]
Thank you for reporting that! 

It seems that some extra spaces got inserted in the config file during copy-pasting. 

Fixed in f54bde7a8bd619eb7ec2516485e972710160ebd4 .
